name: 'Reviewer lottery'
description: 'Automatically assign reviewers to Pull Requests'
author: 'Unai Esteibar'
branding:
  icon: 'eye'
  color: 'orange'
inputs:
  repo-token:
    description: "Github token secret"
    required: true
  config:
    description: 'Path to config file'
    default: '.github/reviewer-lottery.yml'
  pr-author:
    description: 'Pull request author username (optional, will be fetched from API if not provided)'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
